#ifndef __ONPOKER_UTIL_DATABASETYPE_HEADER__
#define __ONPOKER_UTIL_DATABASETYPE_HEADER__
namespace ONEPOKER{

	static const char * DB_DATA_ENUM[] = {"X", "O"};

	enum DB_DATA_TYPE{
		EMAIL_CERT_NO = 0,
		EMAIL_CERT_YES 
	};
	

	enum USER_TB{
		USER_NUM = 0,
		USER_ID,
		USER_PWD,
		USER_EMAIL,
		USER_EMAIL_CERT,
		USER_RESENT_ACCESS_DATE,
		USER_MONEY,
		USER_WIN,
		USER_LOSE,
		USER_RATING
	};

	enum CARD_LIST_TB{
		CARD_NAME = 0,
		CARD_TYPE,
		CARD_WIN
	};

};	
#endif
