#ifndef __ONEPOKER_UTIL_PROTOCOL_HEADER__
#define __ONEPOKER_UTIL_PROTOCOL_HEADER__

namespace CARDGAME{
	enum PROTOCOL_METHOD{
		USER_LOGIN =	0b00000001,
		USER_ADD = 	0b00000010,
		USER_DEL = 	0b00000100,
		USER_CERT =	0b00001000,//CERT 메소드는 유저 인증, 정보 요청, 비밀번호 찾기 등에 사용됨.
		MATCH = 	0b00010000,
		JOIN = 		0b00100000,
		GAME =		0b01000000,
		METHOD_ERROR = 	0b10000000
	};

	enum PROTOCOL_TYPE{
		REQUEST =	USER_LOGIN | USER_ADD | USER_DEL | USER_CERT,
		SUCCESS =	USER_LOGIN | USER_ADD | USER_DEL | USER_CERT,
		FAILED =	USER_LOGIN | USER_ADD | USER_DEL | USER_CERT,
		START = 	MATCH,
		WAIT = 		USER_LOGIN | MATCH,
		READY = 	JOIN ,
		CARD = 		GAME,
		ORDER = 	GAME,
		COMMAND = 	GAME,
		FINISH = 	GAME,
		CHAT = 		GAME,
		TYPE_ERROR = 	METHOD_ERROR
	};
};
#endif
